### ISSUE TITLE
Jar file use

### ISSUE THREAD

**Issue by santoshdbhosale** [compomics/jsparklines#4]
Hello Developers,
I have the jar file but I'm unable to import the spreadsheet data into the GUI of jsparklines. 
Correct me if I'm wrong.
Thanks, Santosh

**Comment by hbarsnes** [comment]
Hi Santosh,

The JSparklines GUI is only for showing the types of sparklines that are supported. Hence you cannot upload your own data to it. To use JSparklines you need to implement your own Java code. Please see the tutorial for more details: https://github.com/compomics/jsparklines/wiki/Tutorial.

Best regards,
Harald

**Comment by santoshdbhosale** [comment]
Thank you for the swift reply!
